### Dependencies

In [1]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import Imputer
from sklearn.cross_validation import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score

/Users/chasekregor/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

### Loading & Cleaning Data

In [2]:
modelb = pd.read_csv('modelb/modelb1ml.csv')

In [3]:
#modelb = modelb.astype(float)

In [4]:
modelb = modelb.pivot_table(index = ['userId'], columns='titles', values = 'rating')

In [5]:
modelb = modelb.reset_index()
modelb.head(10)

titles,userId,"""Great Performances"" Cats (1998)",$5 a Day (2008),'71 (2014),'Hellboy': The Seeds of Creation (2004),'Neath the Arizona Skies (1934),'R Xmas (2001),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),...,[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),eXistenZ (1999),loudQUIETloud: A Film About the Pixies (2006),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nos amours (1983),À nous la liberté (Freedom for Us) (1931)
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN
7,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
for column in modelb:
    modelb[column].fillna((modelb[column].mean()), inplace=True)
    
#modelb = modelb.fillna(2.5)
modelb.head(10)

titles,userId,"""Great Performances"" Cats (1998)",$5 a Day (2008),'71 (2014),'Hellboy': The Seeds of Creation (2004),'Neath the Arizona Skies (1934),'R Xmas (2001),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),...,[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),eXistenZ (1999),loudQUIETloud: A Film About the Pixies (2006),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nos amours (1983),À nous la liberté (Freedom for Us) (1931)
0,1,2.875,3.3,3.0,3.125,3.5,3.0,3.785714,2.75,2.851351,...,3.716981,3.416667,2.5,3.321942,4.5,2.953917,2.533333,3.139241,2.0,3.6
1,2,2.875,3.3,3.0,3.125,3.5,3.0,3.785714,2.75,2.851351,...,3.716981,3.416667,2.5,3.321942,4.5,2.953917,2.533333,3.139241,2.0,3.6
2,3,2.875,3.3,3.0,3.125,3.5,3.0,3.785714,2.75,2.851351,...,3.716981,3.416667,2.5,3.321942,4.5,2.953917,2.533333,3.139241,2.0,3.6
3,4,2.875,3.3,3.0,3.125,3.5,3.0,3.785714,2.75,2.851351,...,3.716981,3.416667,2.5,3.321942,4.5,2.953917,2.533333,3.139241,2.0,3.6
4,5,2.875,3.3,3.0,3.125,3.5,3.0,3.785714,2.75,2.851351,...,3.716981,3.416667,2.5,3.321942,4.5,2.953917,2.533333,3.139241,2.0,3.6
5,6,2.875,3.3,3.0,3.125,3.5,3.0,3.785714,2.75,2.851351,...,3.716981,3.416667,2.5,3.321942,4.5,2.953917,2.533333,3.139241,2.0,3.6
6,7,2.875,3.3,3.0,3.125,3.5,3.0,3.785714,2.75,2.851351,...,3.716981,3.416667,2.5,3.321942,4.5,2.953917,2.533333,2.000000,2.0,3.6
7,8,2.875,3.3,3.0,3.125,3.5,3.0,3.785714,2.75,2.851351,...,3.716981,3.416667,2.5,3.321942,4.5,2.953917,2.533333,3.139241,2.0,3.6
8,9,2.875,3.3,3.0,3.125,3.5,3.0,3.785714,2.75,2.851351,...,3.716981,3.416667,2.5,3.321942,4.5,2.953917,2.533333,3.139241,2.0,3.6
9,10,2.875,3.3,3.0,3.125,3.5,3.0,3.785714,2.75,2.851351,...,3.716981,3.416667,2.5,3.321942,4.5,2.953917,2.533333,3.139241,2.0,3.6

### Building Machine Learning Model

In [7]:
"""test, train = np.split(modelb, [int(.2*len(modelb))])
train.head(10)"""

'test, train = np.split(modelb, [int(.2*len(modelb))])\ntrain.head(10)'

In [8]:
"""clusters = range(1,5)

for i in clusters: 
    
    #not sure why I would have the random state. Ask Dr. Paul about that
    #kmeans = KMeans(n_clusters=18).fit(modelb)
    kmeans = KMeans(n_clusters=i, random_state=0).fit(train)
    print("Fit Model #:")
    print(i)
    
    predictions = kmeans.predict(test)
    
    scores = cross_val_score(kmeans, test,train, cv = 10, scoring= 'accuracy')
    #print(scores)
    print(scores.mean())"""

'clusters = range(1,5)\n\nfor i in clusters: \n    \n    #not sure why I would have the random state. Ask Dr. Paul about that\n    #kmeans = KMeans(n_clusters=18).fit(modelb)\n    kmeans = KMeans(n_clusters=i, random_state=0).fit(train)\n    print("Fit Model #:")\n    print(i)\n    \n    predictions = kmeans.predict(test)\n    \n    scores = cross_val_score(kmeans, test,train, cv = 10, scoring= \'accuracy\')\n    #print(scores)\n    print(scores.mean())'

In [10]:
#not sure why I would have the random state. Ask Dr. Paul about that
#kmeans = KMeans(n_clusters=18).fit(modelb)
kmeans = KMeans(n_clusters=18, random_state=0).fit(modelb)

In [11]:
modelsize = len(modelb.columns)
modelsize

13946

### Creating a Fake User with Fake Ratings

In [18]:
#creates a fake user with random ratings
userratings = np.random.randint(low = 0, high = 5, size=modelsize)
userratings = [userratings]
userratings

[array([3, 0, 3, ..., 2, 0, 0])]

In [19]:
#predict's what cluster our fake user is in
userscluster = kmeans.predict(userratings)
userscluster = userscluster[0]
userscluster

9

In [20]:
prediction = kmeans.cluster_centers_[userscluster]
prediction

array([187.5       ,   2.87533422,   3.3       , ...,   3.14242199,
         2.        ,   3.6       ])

In [21]:
sort_index = np.argsort(prediction)
top20 = sort_index[-21:-1]
top20

array([ 6592,  1401, 10728,  1706, 13316,  7091,  1480, 13282, 13277,
        1516,  6941, 10559,  6873,  6839,  6798,  6754,  6751,  1654,
        6690, 10694])

In [22]:
movietitles = modelb.columns
movietitles

Index(['userId', '"Great Performances" Cats (1998)', '$5 a Day (2008)',
       ''71 (2014)', ''Hellboy': The Seeds of Creation (2004)',
       ''Neath the Arizona Skies (1934)', ''R Xmas (2001)',
       ''Round Midnight (1986)', ''Salem's Lot (2004)',
       ''Til There Was You (1997)',
       ...
       '[REC] (2007)', '[REC]² (2009)', '[REC]³ 3 Génesis (2012)',
       'eXistenZ (1999)', 'loudQUIETloud: A Film About the Pixies (2006)',
       'xXx (2002)', 'xXx: State of the Union (2005)', '¡Three Amigos! (1986)',
       'À nos amours (1983)', 'À nous la liberté (Freedom for Us) (1931)'],
      dtype='object', name='titles', length=13946)

### Fake User's Top 20 Recomendations

In [23]:
for i in top20:
    print(movietitles[i])

Jesus (1979)
Beyond the Clouds (Al di là delle nuvole) (1996)
Satan's Tango (Sátántangó) (1994)
Bob Funk (2009)
Watch Out, We're Mad (...Altrimenti ci arrabbiamo!) (1974)
Last Circus, The (Balada triste de trompeta) (Sad Trumpet Ballad, A) (2010)
Bigger Than the Sky (2005)
War and Peace (Jang Aur Aman) (2001)
War Stories (1995)
Birdemic: Shock and Terror (2010)
Kiss Them for Me (1957)
Ruby & Quentin (Tais-toi!) (2003)
Killing of Sister George, The (1968)
Kiler (1997)
Keith (2008)
Justice League: War (2014)
Justice League: Doom (2012)
Blood on the Sun (1945)
Jubilee (1977)
Samurai Assassin (Samurai) (1965)