In [1]:
import pandas as pd
import numpy as np
import sqlite3

In [2]:
conn = sqlite3.connect(r"movielense20million.db")

In [3]:
model = pd.read_sql_query("""SELECT movieId, 
userId, 
tagId, 
relevance, 
rating 

FROM ratings INNER JOIN (SELECT * FROM genomescores LIMIT 100) as genomescores 

ON ratings.movie2Id = genomescores.movieId 

GROUP BY userId,movieId 

ORDER BY movieId ASC;""", conn)

In [4]:
model

       movieId  userId  tagId  relevance  rating
0            1       3    100    0.10775     4.0
1            1       6    100    0.10775     5.0
2            1       8    100    0.10775     4.0
3            1      10    100    0.10775     4.0
4            1      11    100    0.10775     4.5
5            1      12    100    0.10775     4.0
6            1      13    100    0.10775     4.0
7            1      14    100    0.10775     4.5
8            1      16    100    0.10775     3.0
9            1      19    100    0.10775     5.0
10           1      22    100    0.10775     3.0
11           1      23    100    0.10775     4.0
12           1      24    100    0.10775     4.0
13           1      31    100    0.10775     3.0
14           1      34    100    0.10775     5.0
15           1      39    100    0.10775     5.0
16           1      47    100    0.10775     1.0
17           1      53    100    0.10775     4.0
18           1      54    100    0.10775     4.0
19           1      58    100    0.10775     5.0
20           1      59    100    0.10775     4.5
21           1      66    100    0.10775     4.0
22           1      69    100    0.10775     4.0
23           1      80    100    0.10775     3.0
24           1      82    100    0.10775     5.0
25           1      84    100    0.10775     5.0
26           1      90    100    0.10775     3.5
27           1      91    100    0.10775     4.0
28           1      93    100    0.10775     5.0
29           1      96    100    0.10775     3.5
...        ...     ...    ...        ...     ...
49665        1  138424    100    0.10775     5.0
49666        1  138428    100    0.10775     5.0
49667        1  138430    100    0.10775     2.0
49668        1  138431    100    0.10775     5.0
49669        1  138432    100    0.10775     4.0
49670        1  138436    100    0.10775     3.5
49671        1  138437    100    0.10775     4.0
49672        1  138439    100    0.10775     4.0
49673        1  138441    100    0.10775     5.0
49674        1  138443    100    0.10775     3.5
49675        1  138445    100    0.10775     4.0
49676        1  138446    100    0.10775     5.0
49677        1  138448    100    0.10775     5.0
49678        1  138454    100    0.10775     5.0
49679        1  138456    100    0.10775     1.0
49680        1  138459    100    0.10775     2.0
49681        1  138464    100    0.10775     4.0
49682        1  138467    100    0.10775     4.0
49683        1  138471    100    0.10775     4.5
49684        1  138472    100    0.10775     3.0
49685        1  138473    100    0.10775     4.5
49686        1  138474    100    0.10775     5.0
49687        1  138477    100    0.10775     3.0
49688        1  138480    100    0.10775     4.0
49689        1  138481    100    0.10775     4.0
49690        1  138483    100    0.10775     4.0
49691        1  138486    100    0.10775     5.0
49692        1  138488    100    0.10775     3.0
49693        1  138491    100    0.10775     2.0
49694        1  138493    100    0.10775     3.5

[49695 rows x 5 columns]

In [14]:
for row in (model.userId, model.movieId):
    model[row[model.tagId]] = row[model.relevance]

KeyError: '[296 296 296 ..., 296 296 296] not in index'

In [ ]:

model1 = pd.read_sql_query("""SELECT movieId, 
userId, 
tagId, 
relevance, 
rating 

FROM ratings INNER JOIN (SELECT * FROM genomescores LIMIT 100000) as genomescores 

ON ratings.movie2Id = genomescores.movieId 

GROUP BY userId,movieId 

ORDER BY movieId ASC;""", conn)

In [ ]:
model1

In [ ]:
model1.movieId.value_counts()

In [ ]:
for row in (model.userId, model.movieId):
    model[row['tagId']] = row[model.relevance]

## Machine Learning Model

In [20]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [19]:
regr = linear_model.LinearRegression()

X_train, X_test, y_train, y_test = train_test_split(features, rating, test_size=0.3, random_state=42)

# Train the model using the training sets
regr.fit(X_train, y_train)

# Make predictions using the testing set
movies_y_pred = regr.predict(X_test)

accuracy_score(y_true, movies_y_pred, normalize=False)

NameError: name 'features' is not defined